package br.com.martins.edson.spring.marvel.game.test.util;

import java.time.LocalDateTime;
import java.time.ZoneOffset;
import java.util.Arrays;
import java.util.Date;

import br.com.martins.edson.spring.marvel.game.model.Comic;
import br.com.martins.edson.spring.marvel.game.model.Data;
import br.com.martins.edson.spring.marvel.game.model.Event;
import br.com.martins.edson.spring.marvel.game.model.Item;
import br.com.martins.edson.spring.marvel.game.model.Result;
import br.com.martins.edson.spring.marvel.game.model.Root;
import br.com.martins.edson.spring.marvel.game.model.Serie;
import br.com.martins.edson.spring.marvel.game.model.Story;
import br.com.martins.edson.spring.marvel.game.model.Thumbnail;
import br.com.martins.edson.spring.marvel.game.model.Url;

public class RootCreator {

public static Root retrieveAllRoot() {
		
		return new Root(/* code            */ 0, 
      			 	 	/* status 		   */ "Ok", 
      			 	 	/* copyright 	   */ "© 2021 MARVEL", "Data provided by Marvel. © 2021 MARVEL", 
      			 	 	/* attributionText */ "<a href=\"http://marvel.com\">Data provided by Marvel. © 2021 MARVEL</a>", 
      			 	 	/* attributionHTML */ "413b4ca08ac5c89f64f1a4d2b9b6e864c811daac",
      			 	 	/* data            */ new Data(/* offset */  0,
      			 	 								   /* limit */   20, 
      			 	 								   /* total */   1493, 
      			 	 								   /* count */   20, 
      			 	 								   /* results */ Arrays.asList(new Result(/* id          */ 1009144, 
   			 						 				  										  /* name        */ "A.I.M.",
   			 						 				  										  /* description */ "AIM is a terrorist organization bent on destroying the world.", 
   			 						 				  										  /* modified    */ Date.from(LocalDateTime.now().toInstant(ZoneOffset.UTC)), 
   			 						 				  										  /* thumbnail   */ new Thumbnail(/* path      */ "http://i.annihil.us/u/prod/marvel/i/mg/6/20/52602f21f29ec",
   			 						 				  												  						  /* extension */ "jpg"),
   			 						 				  										  /* resourceURI */ "http://gateway.marvel.com/v1/public/characters/1009144",
   			 						 				  										  /* comics      */ new Comic(/* available     */ 3, 
   			 						 				  												  					  /* collectionURI */ "http://gateway.marvel.com/v1/public/characters/1009144/comics", 
   			 						 				  												  					  /* items         */ Arrays.asList( new Item(/* resourceURI */ "http://gateway.marvel.com/v1/public/comics/36763", 
   			 						 				  												  							  									  /* name        */ "Ant-Man & the Wasp (2010) #3", 
   			 						 				  												  							  									  /* type        */ null), 
   			 						 				  												  							  							 new Item(/* resourceURI */ "http://gateway.marvel.com/v1/public/comics/17553", 
   			 						 				  												  							  									  /* name        */ "Avengers (1998) #67", 
   			 						 				  												  							  									  /* type        */ null), 
   			 						 				  												  							  							 new Item(/* resourceURI */ "http://gateway.marvel.com/v1/public/comics/7340", 
   			 						 				  												  							  									  /* name        */ "Avengers (1963) #87", 
   			 						 				  												  							  									  /* type        */ null)), 
   			 						 				  												  					  /* returned      */ 3),									 
   			 						 				  										  /* series */      new Serie(/* available     */ 3, 
   			 						 				  												  					  /* collectionURI */ "http://gateway.marvel.com/v1/public/characters/1009144/series", 
   			 						 				  												  					  /* items         */ Arrays.asList(new Item(/* resourceURI */ "http://gateway.marvel.com/v1/public/series/13082", 
																	 							  								   									 /* name        */ "Ant-Man & the Wasp (2010 - 2011)", 
																	 							  								   									 /* type        */ null), 
																									 							 	   					    new Item(/* resourceURI */ "http://gateway.marvel.com/v1/public/series/1991", 
																									 							 	   							     /* name        */ "Avengers (1963 - 1996)", 
																									 							 	   							     /* type        */ null), 
																									 							 	   					    new Item(/* resourceURI */ "http://gateway.marvel.com/v1/public/series/354", 
																									 							 	   							     /* name        */ "Avengers (1998 - 2004)", 
																									 							 	   							     /* type        */ null)), 
   			 						 				  												  					  /* returned      */ 3),
   			 						 				  										  /* stories */     new Story(/* available     */ 3, 
   			 						 				  												  					  /* collectionURI */ "http://gateway.marvel.com/v1/public/characters/1009144/stories", 
   			 						 				  												  					  /* items         */ Arrays.asList(new Item(/* resourceURI */ "http://gateway.marvel.com/v1/public/stories/5800", 
																  								   																	 /* name        */ "Avengers and Power Pack Assemble! (2006) #2", 
																  								   																	 /* type        */ "cover"),
																									 							 						    new Item(/* resourceURI */ "http://gateway.marvel.com/v1/public/stories/5801", 
																									 							 								     /* name        */ "2 of 4 - 4XLS", 
																									 							 								     /* type        */ "interiorStory"),
																									 							 						    new Item(/* resourceURI */ "http://gateway.marvel.com/v1/public/stories/10253", 
																									 							 								     /* name        */ "When the Unliving Strike", 
																									 							 								     /* type        */ "interiorStory")), 
   			 						 				  												  					  /* returned      */ 4),
   			 						 				  										  /* events */      new Event(/* available     */ 0, 
   			 						 				  												  					  /* collectionURI */ "http://gateway.marvel.com/v1/public/characters/1009144/events", 
   			 						 				  												  					  /* items         */ null, 
   			 						 				  												  					  /* returned      */ 0),
   			 						 				  										  /* urls */         Arrays.asList(new Url(/* type */ "detail", 
   			 						 				  												  								   /* url  */ "http://marvel.com/comics/characters/1009144/aim.?utm_campaign=apiRef&utm_source=eee625a313cc22a00db5e7d5329ee5c1"),
																							 								   new Url(/* type */ "wiki", 
																							 										   /* url  */ "http://marvel.com/universe/A.I.M.?utm_campaign=apiRef&utm_source=eee625a313cc22a00db5e7d5329ee5c1"))),
					      			 	 										   new Result(/* id          */ 1017100, 
									 				  										  /* name        */ "A-Bomb (HAS)",
									 				  										  /* description */ "Rick Jones has been Hulk's best bud since day one, but now he's more than a friend...he's a teammate! Transformed by a Gamma energy explosion, A-Bomb's thick, armored skin is just as strong and powerful as it is blue. And when he curls into action, he uses it like a giant bowling ball of destruction! ", 
									 				  										  /* modified    */ Date.from(LocalDateTime.now().toInstant(ZoneOffset.UTC)), 
									 				  										  /* thumbnail   */ new Thumbnail(/* path      */ "http://i.annihil.us/u/prod/marvel/i/mg/3/20/5232158de5b16",
									 				  												  						  /* extension */ "jpg"),
									 				  										  /* resourceURI */ "http://gateway.marvel.com/v1/public/characters/1017100",
									 				  										  /* comics      */ new Comic(/* available     */ 3, 
									 				  												  					  /* collectionURI */ "http://gateway.marvel.com/v1/public/characters/1017100/comics", 
									 				  												  					  /* items         */ Arrays.asList( new Item(/* resourceURI */ "http://gateway.marvel.com/v1/public/comics/40632", 
									 				  												  							  									  /* name        */ "Hulk (2008) #53", 
									 				  												  							  									  /* type        */ null), 
									 				  												  							  							 new Item(/* resourceURI */ "http://gateway.marvel.com/v1/public/comics/40630", 
									 				  												  							  									  /* name        */ "Hulk (2008) #54", 
									 				  												  							  									  /* type        */ null), 
									 				  												  							  							 new Item(/* resourceURI */ "http://gateway.marvel.com/v1/public/comics/40628", 
									 				  												  							  									  /* name        */ "Hulk (2008) #55", 
									 				  												  							  									  /* type        */ null)), 
									 				  												  					  /* returned      */ 3),									 
									 				  										  /* series */      new Serie(/* available     */ 2, 
									 				  												  					  /* collectionURI */ "http://gateway.marvel.com/v1/public/characters/1017100/series", 
									 				  												  					  /* items         */ Arrays.asList(new Item(/* resourceURI */ "http://gateway.marvel.com/v1/public/series/17765", 
																 							  								   									 	 /* name        */ "FREE COMIC BOOK DAY 2013 1 (2013)", 
																 							  								   									 	 /* type        */ null), 
																								 							 	   					    	new Item(/* resourceURI */ "http://gateway.marvel.com/v1/public/series/3374", 
																								 							 	   					    			 /* name        */ "Hulk (2008 - 2012)", 
																								 							 	   					    			 /* type        */ null)), 
									 				  												  					  /* returned      */ 2),
									 				  										  /* stories */     new Story(/* available     */ 3, 
									 				  												  					  /* collectionURI */ "http://gateway.marvel.com/v1/public/characters/1017100/stories", 
									 				  												  					  /* items         */ Arrays.asList(new Item(/* resourceURI */ "http://gateway.marvel.com/v1/public/stories/92078", 
									 				  												  							  									 /* name        */ "Hulk (2008) #55", 
									 				  												  							  									 /* type        */ "cover"),
									 				  												  							  							new Item(/* resourceURI */ "http://gateway.marvel.com/v1/public/stories/92079", 
									 				  												  							  									 /* name        */ "Interior #92079", 
									 				  												  							  									 /* type        */ "interiorStory"),
									 				  												  							  							new Item(/* resourceURI */ "http://gateway.marvel.com/v1/public/stories/92082", 
									 				  												  							  									 /* name        */ "Hulk (2008) #54", 
									 				  												  							  									 /* type        */ "cover")), 
									 				  												  					  /* returned      */ 3),
									 				  										  /* events */      new Event(/* available     */ 0, 
									 				  												  					  /* collectionURI */ "http://gateway.marvel.com/v1/public/characters/1017100/events", 
									 				  												  					  /* items         */ null, 
									 				  												  					  /* returned      */ 0),
									 				  										  /* urls */         Arrays.asList(new Url(/* type */ "detail", 
									 				  												  								   /* url  */ "http://marvel.com/characters/76/a-bomb?utm_campaign=apiRef&utm_source=eee625a313cc22a00db5e7d5329ee5c1"),
																						 								       new Url(/* type */ "comiclink", 
																						 										       /* url  */ "http://marvel.com/comics/characters/1017100/a-bomb_has?utm_campaign=apiRef&utm_source=eee625a313cc22a00db5e7d5329ee5c1"))))));
	}

	public static Root findRootDataById() {
	
		return new Root(/* code            */ 0, 
			 	 	    /* status 		   */ "Ok", 
			 	 	    /* copyright 	   */ "© 2021 MARVEL", "Data provided by Marvel. © 2021 MARVEL", 
			 	 	    /* attributionText */ "<a href=\"http://marvel.com\">Data provided by Marvel. © 2021 MARVEL</a>", 
			 	 	    /* attributionHTML */ "413b4ca08ac5c89f64f1a4d2b9b6e864c811daac",
			 	 	    /* data            */ new Data(/* offset */  0,
			 	 								   	   /* limit */   20, 
			 	 								   	   /* total */   1493, 
			 	 								   	   /* count */   20, 
			 	 								   	   /* results */ Arrays.asList(new Result(/* id          */ 1009144, 
		 						 				  										      /* name        */ "A.I.M.",
		 						 				  										      /* description */ "AIM is a terrorist organization bent on destroying the world.", 
		 						 				  										      /* modified    */ Date.from(LocalDateTime.now().toInstant(ZoneOffset.UTC)), 
		 						 				  										      /* thumbnail   */ new Thumbnail(/* path      */ "http://i.annihil.us/u/prod/marvel/i/mg/6/20/52602f21f29ec",
		 						 				  										    		  						  /* extension */ "jpg"),
		 						 				  										      /* resourceURI */ "http://gateway.marvel.com/v1/public/characters/1009144",
		 						 				  										      /* comics      */ new Comic(/* available     */ 3, 
		 						 				  												  					  	  /* collectionURI */ "http://gateway.marvel.com/v1/public/characters/1009144/comics", 
		 						 				  												  					  	  /* items         */ Arrays.asList( new Item(/* resourceURI */ "http://gateway.marvel.com/v1/public/comics/36763", 
		 						 				  												  							  									  	  /* name        */ "Ant-Man & the Wasp (2010) #3", 
		 						 				  												  							  									  	  /* type        */ null), 
		 						 				  												  							  							 	 new Item(/* resourceURI */ "http://gateway.marvel.com/v1/public/comics/17553", 
		 						 				  												  							  							 			  /* name        */ "Avengers (1998) #67", 
		 						 				  												  							  							 			  /* type        */ null), 
		 						 				  												  							  							 	 new Item(/* resourceURI */ "http://gateway.marvel.com/v1/public/comics/7340", 
		 						 				  												  							  							 			  /* name        */ "Avengers (1963) #87", 
		 						 				  												  							  							 			  /* type        */ null)), 
		 						 				  												  					  	  /* returned      */ 3),									 
		 						 				  										      /* series      */ new Serie(/* available     */ 3, 
		 						 				  										    		  					  /* collectionURI */ "http://gateway.marvel.com/v1/public/characters/1009144/series", 
		 						 				  										    		  					  /* items         */ Arrays.asList(new Item(/* resourceURI */ "http://gateway.marvel.com/v1/public/series/13082", 
															 							  								   									 		 /* name        */ "Ant-Man & the Wasp (2010 - 2011)", 
															 							  								   									 		 /* type        */ null), 
																							 							 	   					    		new Item(/* resourceURI */ "http://gateway.marvel.com/v1/public/series/1991", 
																							 							 	   					    				 /* name        */ "Avengers (1963 - 1996)", 
																							 							 	   					    				 /* type        */ null), 
																							 							 	   					    		new Item(/* resourceURI */ "http://gateway.marvel.com/v1/public/series/354", 
																							 							 	   					    				 /* name        */ "Avengers (1998 - 2004)", 
																							 							 	   					    				 /* type        */ null)), 
		 						 				  										    		  					  /* returned      */ 3),
		 						 				  										      /* stories     */ new Story(/* available     */ 3, 
		 						 				  												  					  	  /* collectionURI */ "http://gateway.marvel.com/v1/public/characters/1009144/stories", 
		 						 				  												  					  	  /* items         */ Arrays.asList(new Item(/* resourceURI */ "http://gateway.marvel.com/v1/public/stories/5800", 
														  								   																	 		 /* name        */ "Avengers and Power Pack Assemble! (2006) #2", 
														  								   																	 		 /* type        */ "cover"),
																							 							 						    		new Item(/* resourceURI */ "http://gateway.marvel.com/v1/public/stories/5801", 
																							 							 						    				 /* name        */ "2 of 4 - 4XLS", 
																							 							 						    				 /* type        */ "interiorStory"),
																							 							 						    		new Item(/* resourceURI */ "http://gateway.marvel.com/v1/public/stories/10253", 
																							 							 						    				 /* name        */ "When the Unliving Strike", 
																							 							 						    				 /* type        */ "interiorStory")), 
		 						 				  												  			 		  	  /* returned      */ 4),
		 						 				  										      /* events      */ new Event(/* available     */ 0, 
		 						 				  												  					  	  /* collectionURI */ "http://gateway.marvel.com/v1/public/characters/1009144/events", 
		 						 				  												  					  	  /* items         */ null, 
		 						 				  												  					  	  /* returned      */ 0),
		 						 				  										      /* urls        */ Arrays.asList(new Url(/* type */ "detail", 
		 						 				  												  								      /* url  */ "http://marvel.com/comics/characters/1009144/aim.?utm_campaign=apiRef&utm_source=eee625a313cc22a00db5e7d5329ee5c1"),
																					 								   		  new Url(/* type */ "wiki", 
																					 								   				  /* url  */ "http://marvel.com/universe/A.I.M.?utm_campaign=apiRef&utm_source=eee625a313cc22a00db5e7d5329ee5c1"))))));
	}

	public static Root findAllAndReturnOneNullResultData() {
		
		return new Root(/* code            */ 0, 
				 	 	/* status 		   */ "Ok", 
				 	 	/* copyright 	   */ "© 2021 MARVEL", "Data provided by Marvel. © 2021 MARVEL", 
				 	 	/* attributionText */ "<a href=\"http://marvel.com\">Data provided by Marvel. © 2021 MARVEL</a>", 
				 	 	/* attributionHTML */ "413b4ca08ac5c89f64f1a4d2b9b6e864c811daac",
				 	 	/* data            */ new Data(/* offset */  0,
				 	 								   /* limit */   20, 
				 	 								   /* total */   1493, 
				 	 								   /* count */   20, 
				 	 								   /* results */ Arrays.asList(null,
				      			 	 										   new Result(/* id          */ 1017100, 
								 				  										  /* name        */ "A-Bomb (HAS)",
								 				  										  /* description */ "Rick Jones has been Hulk's best bud since day one, but now he's more than a friend...he's a teammate! Transformed by a Gamma energy explosion, A-Bomb's thick, armored skin is just as strong and powerful as it is blue. And when he curls into action, he uses it like a giant bowling ball of destruction! ", 
								 				  										  /* modified    */ Date.from(LocalDateTime.now().toInstant(ZoneOffset.UTC)), 
								 				  										  /* thumbnail   */ new Thumbnail(/* path      */ "http://i.annihil.us/u/prod/marvel/i/mg/3/20/5232158de5b16",
								 				  												  						  /* extension */ "jpg"),
								 				  										  /* resourceURI */ "http://gateway.marvel.com/v1/public/characters/1017100",
								 				  										  /* comics      */ new Comic(/* available     */ 3, 
								 				  												  					  /* collectionURI */ "http://gateway.marvel.com/v1/public/characters/1017100/comics", 
								 				  												  					  /* items         */ Arrays.asList( new Item(/* resourceURI */ "http://gateway.marvel.com/v1/public/comics/40632", 
								 				  												  							  									  /* name        */ "Hulk (2008) #53", 
								 				  												  							  									  /* type        */ null), 
								 				  												  							  							 new Item(/* resourceURI */ "http://gateway.marvel.com/v1/public/comics/40630", 
								 				  												  							  									  /* name        */ "Hulk (2008) #54", 
								 				  												  							  									  /* type        */ null), 
								 				  												  							  							 new Item(/* resourceURI */ "http://gateway.marvel.com/v1/public/comics/40628", 
								 				  												  							  									  /* name        */ "Hulk (2008) #55", 
								 				  												  							  									  /* type        */ null)), 
								 				  												  					  /* returned      */ 3),									 
								 				  										  /* series */      new Serie(/* available     */ 2, 
								 				  												  					  /* collectionURI */ "http://gateway.marvel.com/v1/public/characters/1017100/series", 
								 				  												  					  /* items         */ Arrays.asList(new Item(/* resourceURI */ "http://gateway.marvel.com/v1/public/series/17765", 
															 							  								   									 	 /* name        */ "FREE COMIC BOOK DAY 2013 1 (2013)", 
															 							  								   									 	 /* type        */ null), 
																							 							 	   					    	new Item(/* resourceURI */ "http://gateway.marvel.com/v1/public/series/3374", 
																							 							 	   					    			 /* name        */ "Hulk (2008 - 2012)", 
																							 							 	   					    			 /* type        */ null)), 
								 				  												  					  /* returned      */ 2),
								 				  										  /* stories */     new Story(/* available     */ 3, 
								 				  												  					  /* collectionURI */ "http://gateway.marvel.com/v1/public/characters/1017100/stories", 
								 				  												  					  /* items         */ Arrays.asList(new Item(/* resourceURI */ "http://gateway.marvel.com/v1/public/stories/92078", 
								 				  												  							  									 /* name        */ "Hulk (2008) #55", 
								 				  												  							  									 /* type        */ "cover"),
								 				  												  							  							new Item(/* resourceURI */ "http://gateway.marvel.com/v1/public/stories/92079", 
								 				  												  							  									 /* name        */ "Interior #92079", 
								 				  												  							  									 /* type        */ "interiorStory"),
								 				  												  							  							new Item(/* resourceURI */ "http://gateway.marvel.com/v1/public/stories/92082", 
								 				  												  							  									 /* name        */ "Hulk (2008) #54", 
								 				  												  							  									 /* type        */ "cover")), 
								 				  												  					  /* returned      */ 3),
								 				  										  /* events */      new Event(/* available     */ 0, 
								 				  												  					  /* collectionURI */ "http://gateway.marvel.com/v1/public/characters/1017100/events", 
								 				  												  					  /* items         */ null, 
								 				  												  					  /* returned      */ 0),
								 				  										  /* urls */         Arrays.asList(new Url(/* type */ "detail", 
								 				  												  								   /* url  */ "http://marvel.com/characters/76/a-bomb?utm_campaign=apiRef&utm_source=eee625a313cc22a00db5e7d5329ee5c1"),
																					 								       new Url(/* type */ "comiclink", 
																					 										       /* url  */ "http://marvel.com/comics/characters/1017100/a-bomb_has?utm_campaign=apiRef&utm_source=eee625a313cc22a00db5e7d5329ee5c1"))))));
			

	}
	
public static Root findAllAndReturnTwoNullResultData() {
		
		return new Root(/* code            */ 0, 
				 	 	/* status 		   */ "Ok", 
				 	 	/* copyright 	   */ "© 2021 MARVEL", "Data provided by Marvel. © 2021 MARVEL", 
				 	 	/* attributionText */ "<a href=\"http://marvel.com\">Data provided by Marvel. © 2021 MARVEL</a>", 
				 	 	/* attributionHTML */ "413b4ca08ac5c89f64f1a4d2b9b6e864c811daac",
				 	 	/* data            */ new Data(/* offset */  0,
				 	 								   /* limit */   20, 
				 	 								   /* total */   1493, 
				 	 								   /* count */   20, 
				 	 								   /* results */ Arrays.asList(null, null)));
			

	}
}
